In [2]:
import pandas as pd

# Load CSV file and skip the description row
df = pd.read_csv("student_scores.csv", skiprows=1)

# Display dataset information
print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nFirst 10 rows:")
display(df.head(10))

Shape: (9, 2)

Data Types:
Hours_studied    int64
marks            int64
dtype: object

First 10 rows:

   Hours_studied  marks
0              2     45
1              3     50
2              4     55
3              5     65
4              6     70
5              7     78
6              8     85
7              9     90
8             10     95

In [3]:
# Filter: select students who scored 70 or above
filtered_df = df[df["marks"] >= 70]

print("Students with marks >= 70:")
display(filtered_df)

Students with marks >= 70:

   Hours_studied  marks
4              6     70
5              7     78
6              8     85
7              9     90
8             10     95

In [4]:
# Groupby: calculate average marks for each number of study hours
grouped_df = df.groupby("Hours_studied")["marks"].mean()

print("Average marks by study hours:")
display(grouped_df)

Average marks by study hours:

Hours_studied
2     45.0
3     50.0
4     55.0
5     65.0
6     70.0
7     78.0
8     85.0
9     90.0
10    95.0
Name: marks, dtype: float64

In [5]:
# Merge: create a second DataFrame with student categories
student_info = pd.DataFrame({
    "Hours_studied": [2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Category": ["Low", "Low", "Low", "Medium", "Medium",
                 "High", "High", "High", "High"]
})

merged_df = pd.merge(df, student_info, on="Hours_studied", how="inner")

print("Merged DataFrame:")
display(merged_df)

Merged DataFrame:

   Hours_studied  marks Category
0              2     45      Low
1              3     50      Low
2              4     55      Low
3              5     65   Medium
4              6     70   Medium
5              7     78     High
6              8     85     High
7              9     90     High
8             10     95     High

In [6]:
# Pivot table: show average marks for each student category
pivot_df = pd.pivot_table(
    merged_df,
    values="marks",
    index="Category",
    aggfunc="mean"
)

print("Average marks by category:")
display(pivot_df)

Average marks by category:

          marks
Category
High       87.0
Low        50.0
Medium     67.5

In [3]:
df.to_parquet("cleaned_student_scores.parquet", index=False)

print("Parquet file created successfully.")

Parquet file created successfully.

In [4]:
import os

csv_size = os.path.getsize("cleaned_student_scores.csv")
parquet_size = os.path.getsize("cleaned_student_scores.parquet")

print("CSV size:", csv_size, "bytes")
print("Parquet size:", parquet_size, "bytes")

CSV size: 76 bytes
Parquet size: 1891 bytes

In [5]:
df_parquet = pd.read_parquet("cleaned_student_scores.parquet")

print(df_parquet)

   Hours_studied  marks
0              2     45
1              3     50
2              4     55
3              5     65
4              6     70
5              7     78
6              8     85
7              9     90
8             10     95

In [6]:
print("Original shape:", df.shape)
print("Parquet shape:", df_parquet.shape)

print("Data is identical:", df.equals(df_parquet))

Original shape: (9, 2)
Parquet shape: (9, 2)
Data is identical: True